### ISSUE TITLE
bluesky => fedi: RE: ... links for quote posts not appearing in Mastodon

### ISSUE THREAD

**Issue by agoldst** [snarfed/bridgy-fed#2169]
mastodon introduced quote posts. The quoting interaction with bluesky over the bridge is probably pretty complex. I noticed these changes:

- a bridged bluesky account quoting itself in a post appears as a mastodon quote post: super neat! (does this work when one bridged account quotes another? but I haven't seen any examples)
- bridged bluesky quote-posts used to appear on mastodon with a link to the quoted post ("RE: ..."). That was a good fallback. Now those links are gone and I just see the quoter's comment, with no indication that it's a quote post. Any way to leave some kind of placeholder?
- posts bridged from bluesky seem not to be quotable on mastodon--can individual users change that?

Thanks as always for the heroic work of trying to make things hang together.

**Comment by snarfed** [comment]
Yes! Lots of background in #1956. The one surprise to me here is that quote posts no longer show the RE: ... link on Mastodon. That's an unfortunate recent change. Hrm. Thanks for reporting, will investigate.

**Comment by agoldst** [comment]
Thank you! Would be great to get those "RE: ..." links back if you are able. The info in #1956 is fascinating (and explains the bridged-self-quote working). Following the drift of the comments there, I'd say the most immediately desirable feature in the bsky => mastodon direction would be bridging quoting-enabled bsky users' posts as publicly quotable mastodon posts. The other direction looks like a tangle...

**Comment by jhenstridge** [comment]
It looks like the Mastodon team have treated this as a bug, and merged a fix: https://github.com/mastodon/mastodon/pull/36638

It looks like the problem only existed for a few weeks in 4.5 pre-releases, so would only affect servers running pre-release builds and will likely go away as they upgrade. There might not be anything to fix on this side.

**Comment by snarfed** [comment]
@jhenstridge oh wow, interesting, thank you for digging this up!

**Comment by snarfed** [comment]
Confirmed. I see the RE: ... fallback links on Mastodon v4.4.8, on indieweb.social, but not on v4.5.0-rc.1+pr-36635-27e87e6, on mastodon.social.

<img width="310"  alt="Image" src="https://github.com/user-attachments/assets/43130e98-0e94-4bbd-9556-955efb9e5cc6" />

<img width="309" alt="Image" src="https://github.com/user-attachments/assets/efef6b6b-88be-49db-86ee-7aa5d91abfba" />

Sounds like this should be fixed on mastodon.social etc as soon as they deploy https://github.com/mastodon/mastodon/pull/36638 . Tentatively closing.

**Comment by agoldst** [comment]
Yes, I see the RE: links have returned for posts bridged to mastodon.social as well. Thanks @snarfed @jhenstridge !

**Comment by jernejs** [comment]
The RE: links still don't appear at least on infosec.exchange (running v4.6.0-alpha.3+glitch at the moment). Example:

https://infosec.exchange/@dryad.technology@bsky.brid.gy/116009529766461568
<img width="1052" height="426" alt="Image" src="https://github.com/user-attachments/assets/319540f6-0752-44cb-923d-ba2b0793b754" />

https://bsky.app/profile/did:plc:2aebn3xk5t63net43eeepire/post/3mdymmep2vk2d
<img width="1062" height="1511" alt="Image" src="https://github.com/user-attachments/assets/c016a2c7-d739-429d-bdaf-fd2772f0cf23" />

**Comment by snarfed** [comment]
@jernejs hmm! The RE: link is definitely there in that post: https://browser.pub/https://infosec.exchange/@dryad.technology@bsky.brid.gy/116009529766461568 . I don't know why infosec.exchange isn't rendering it. Maybe custom CSS that hides `.quote-inline`?

**Comment by jernejs** [comment]
Seems to be a problem specific to Glitch: https://github.com/glitch-soc/mastodon/issues/3386
