### ISSUE TITLE
Scale ATProto handle resolution

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#744]
We need to serve [ATProto handle resolution](https://atproto.com/specs/handle#handle-resolution) for all users bridged into ATProto (background: #381). They support both DNS and HTTPS methods, but our ATProto handles are multi-level, eg `@user@mastodon.social` becomes `user.mastodon.social.ap.brid.gy`, and you can't make multi-level wildcard SSL certs, so HTTPS won't work, so DNS it is.

We're currently using [Google Cloud DNS](https://cloud.google.com/dns/). It serves the entire `brid.gy` DNS zone, and we create `_atproto` records for handle resolution manually. The catch is that GCP DNS has a [hard limit of 10k records per zone](https://cloud.google.com/dns/quotas), which we'll likely outgrow. Grr.

We could make a zone per sub-subdomain, eg per fediverse instance, so `mastodon.social.ap.brid.gy` would become its own zone, but GCP DNS also has a hard limit of 10k zones total.

To do:
* [x] #1268 
* [x] delete handles for disabled accounts
* [x] ask for another quota bump, to 100k or 200k

So, we eventually need to switch to a different programmatic DNS service or run our own DNS server. Whee.

**Comment by snarfed** [comment]
Provider lists:
https://en.wikipedia.org/wiki/List_of_managed_DNS_providers
https://www.g2.com/categories/managed-dns-providers
https://serverauth.com/posts/comparing-dns-hosting-providers

**Comment by snarfed** [comment]
Upcoming option: https://dns.kitchen/ , all you can eat zones/records.

**Comment by snarfed** [comment]
@neatnik mentioned https://desec.io/ too.

**Comment by snarfed** [comment]
Also https://dns.he.net/, https://www.nova53.net/, https://ns-global.zone/ .

**Comment by snarfed** [comment]
Maybe obsoleted by #830 🤞

**Comment by snarfed** [comment]
...nope, turns out #830 probably won't work after all, so this issue definitely still applies.

**Comment by snarfed** [comment]
The 10k limit in Google Cloud DNS is a quota, `resourceRecordsPerRrset`, that I can request an increase for. May try that.
* https://cloud.google.com/dns/quotas#quotas
* https://console.cloud.google.com/iam-admin/quotas?service=dns.googleapis.com&metric=dns.googleapis.com%2Fquota%2Fresource_records_per_rrset&project=bridgy-federated

**Comment by snarfed** [comment]
Tried requesting a quota bump. 🤞

**Comment by snarfed** [comment]
In unrelated very good news, @bnewbold built us a whole new microservice to solve this! https://github.com/bluesky-social/atproto/discussions/1697#discussioncomment-9308726 . Extremely generous of him. Thank you Bryan!!!

**Comment by snarfed** [comment]
More good news, I asked for a GCP DNS quota bump to 50k and got it. Woo!

**Comment by snarfed** [comment]
We're currently at 6500 DNS records, with the limit still at 50k. We'll (hopefully) still need to figure this out eventually, but it seems like we have plenty of time.

**Comment by snarfed** [comment]
Count is 28k now! I think a decent number of those are disabled, many but not all from Flipboard.

To do:
* [ ] delete handles for disabled accounts
* [ ] ask for another quota bump, to 100k or 200k

**Comment by louis-lau** [comment]
I have no idea what this software is, but stumbled across this issue while research secondary dns providers. :)

Given the programmatic nature of these records, maybe you'd be better off with something like powerdns with the remote backend?
https://doc.powerdns.com/authoritative/backends/remote.html

Or if you need a managed service, Bunny DNS?
https://bunny.net/dns/

You'd never run into record limitations, as the responses are just created on the fly.

**Comment by bnewbold** [comment]
Here is a direct link to `handlr`, the DNS proxying service I wrote:

https://github.com/bluesky-social/indigo/pull/665

it hasn't been reviewed or merged to `main` branch yet. If I get a chance I can respond to things and try to get it merged, but may or may not be responsive about updating/maintaining it. If bridgy ends up depending on it, might be worth pulling the code out in to a separate repo? I wrote this in spare time and am flexible/amenable to basically any license on the code. Or you could re-write in python for something more familiar/maintainable.

**Comment by shiribailem** [comment]
Just chiming in here as it's related to another I just added a comment to... Have you considered just running your own nameserver?

This would both mean no limits and faster updates as records change among other possible gains?

**Comment by snarfed** [comment]
@shiribailem yes! Definitely considered that, hence "or run our own DNS server" in the original description here. It would mean no limits and faster updates, but it would also mean running and maintaining our own nameserver. One more level of admin cost and risk. Whee.

But yeah we may end up doing that regardless, esp since @bnewbold built us one! https://github.com/snarfed/bridgy-fed/issues/744#issuecomment-2094566152

**Comment by shiribailem** [comment]
I mean the good news is that nameservers are very very low requirements on resources, performance, and effort, even for security.

The worst risk is the fully custom service vs just using internal APIs/config-files to update zones on an established DNS server.

Given that DNS isn't a big attack surface compared to the entire bridge software itself, I wouldn't stress as much over that.

**Comment by snarfed** [comment]
Done! Reclaimed ~13.5k total, currently at 24.5k out of 50k quota.

**Comment by snarfed** [comment]
Requested a quota bump to 200k. 🤞

**Comment by shiribailem** [comment]
just randomly thinking... have you considered stripping periods from the converted usernames? That would make it trivial to switch to HTTPS resolution... Sadly that's something that would be easier at the beginning of the project before you had thousands of users, but I could still see it working.

If you did that, I'd probably leverage the code for setting custom domains and just convert all existing listings to custom domains (which would otherwise leave them unchanged). From there you could just use HTTPS verification going forward.

**Comment by snarfed** [comment]
@shiribailem we have, https://github.com/snarfed/bridgy-fed/issues/744#issuecomment-1938057243, #830

**Comment by snarfed** [comment]
Holy crap, they gave us the quota bump to 200k records! 🎉

**Comment by snarfed** [comment]
A year later, we're at 52k DNS records out of our 200k quota. We should be ok for a while more.
